version: "3.4"

services:
  rabbitmq:
    image: nexus.int.clxnetworks.net:8009/rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge