spring:
  application:
    name: rabbitmq-basic-producer
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

application:
  rabbit:
    exchange: direct
    #topic
    #fanout
    #headers